# Generated by Django 3.2.4 on 2021-06-08 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyAdmin', '0001_initial'),
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAdmin.cake')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.usermaster')),
            ],
            options={
                'db_table': 'Mycart',
            },
        ),
    ]
