# Generated by Django 3.2.4 on 2021-06-08 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cakename', models.CharField(max_length=50)),
                ('price', models.FloatField(default=1000)),
                ('description', models.CharField(max_length=100)),
                ('imageurl', models.ImageField(default='abc.jpg', upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAdmin.category')),
            ],
            options={
                'db_table': 'Cake',
            },
        ),
    ]
